"""add role to user

Revision ID: 172e7ed2198c
Revises: d963c4d89e66
Create Date: 2025-12-29 14:30:15.365572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172e7ed2198c'
down_revision: Union[str, None] = 'd963c4d89e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add column as nullable
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    
    # 2. Update existing rows
    op.execute("UPDATE users SET role = 'editor' WHERE role IS NULL")
    
    # 3. Alter to not null
    op.alter_column('users', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
