"""add_refresh_tokens_table

Revision ID: b5c144fc5e04
Revises: 9c84197411d9
Create Date: 2026-01-09 19:14:02.697368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c144fc5e04'
down_revision: Union[str, None] = '9c84197411d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.drop_index('idx_agents_client_id', table_name='agents')
    op.drop_index('idx_agents_folder_id', table_name='agents')
    op.drop_index('idx_agents_name', table_name='agents')
    op.drop_index('idx_agents_type', table_name='agents')
    op.drop_index('idx_api_keys_client_id', table_name='api_keys')
    op.drop_index('idx_api_keys_is_active', table_name='api_keys')
    op.drop_index('idx_api_keys_provider', table_name='api_keys')
    op.drop_index('idx_users_client_id', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.create_index('idx_users_client_id', 'users', ['client_id'], unique=False)
    op.create_index('idx_api_keys_provider', 'api_keys', ['provider'], unique=False)
    op.create_index('idx_api_keys_is_active', 'api_keys', ['is_active'], unique=False)
    op.create_index('idx_api_keys_client_id', 'api_keys', ['client_id'], unique=False)
    op.create_index('idx_agents_type', 'agents', ['type'], unique=False)
    op.create_index('idx_agents_name', 'agents', ['name'], unique=False)
    op.create_index('idx_agents_folder_id', 'agents', ['folder_id'], unique=False)
    op.create_index('idx_agents_client_id', 'agents', ['client_id'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
