from typing import Any

from pydantic import BaseModel, Field


class FileData(BaseModel):
    """Model to represent file data sent in a chat request."""

    filename: str = Field(..., description="File name")
    content_type: str = Field(..., description="File content type")
    data: str = Field(..., description="File content encoded in base64")


class ChatRequest(BaseModel):
    """Model to represent a chat request."""

    message: str = Field(..., description="User message to the agent")
    agent_id: str | None = Field(None, description="Agent ID to process the message")
    external_id: str | None = Field(None, description="External ID for user identification")
    files: list[FileData] | None = Field(
        None, description="List of files attached to the message"
    )


class ChatResponse(BaseModel):
    """Model to represent a chat response."""

    response: str = Field(..., description="Response generated by the agent")
    message_history: list[dict[str, Any]] = Field(
        default_factory=list, description="Message history"
    )
    status: str = Field(..., description="Response status (success/error)")
    timestamp: str = Field(..., description="Response timestamp")


class ErrorResponse(BaseModel):
    """Model to represent an error response."""

    detail: str = Field(..., description="Error details")
